### ISSUE TITLE
No Gui available after Git-clone

### ISSUE THREAD

**Issue by MarcinKinque** [matsim-scenarios/matsim-stuttgart#35]
Hi,

I'm trying to run the Stuttgart scenario, but after cloning the Stuttgart repository and attempting to run the .jar file, no GUI is appearing. Am I doing something wrong, or can I test this Stuttgart scenario with the Berlin .jar GUI by simply changing the config file? What steps do I need to take to successfully run the Stuttgart scenario? Can someone please help?

**Comment by Janekdererste** [comment]
This repository has no GUI inlcuded. You can run the application by creating a jar file first:
```
$ mvn clean install
```
Then you should be able to run the jar with 
```
$ java -jar ./jar-name.jar run /path/to/config.xml
```
This works like a command line app then. You can add a `--help` parameter, to see all options.
