### ISSUE TITLE
Please remove absolute file paths

### ISSUE THREAD

**Issue by Janekdererste** [matsim-scenarios/matsim-stuttgart#5]
https://github.com/matsim-scenarios/matsim-stuttgart/blob/master/src/main/java/org/matsim/prepare/AddAdditionalNetworkAttributes.java zum Beispiel hier. 

As template you can use this class 

https://github.com/matsim-scenarios/matsim-stuttgart/blob/master/src/main/java/org/matsim/prepare/CreateNetwork.java

It uses JCommander for commandline parsing and an Args class to point the script to the svn root repository

**Comment by davidwedekind** [comment]
Temporarily done with
https://github.com/matsim-scenarios/matsim-stuttgart/commit/92cb6fd95c5b89a0ff0ee75bff60b00f6ad5c89a

ToDo:
Once David has writing access to svn, include a pointer to the root repository.
