### ISSUE TITLE
Remove dependency to la-scenario

### ISSUE THREAD

**Issue by Janekdererste** [matsim-scenarios/matsim-stuttgart#6]
Just, so we don't forget.

Remove as soon as possible. There is the first conflict of dependency versions already

**Comment by davidwedekind** [comment]
Removal possible approx. with next weeks weekly release. Parking cost handler has been moved to vsp-contrib and was extended for the stuttgart case.

**Comment by davidwedekind** [comment]
Had been removed when the handler was moved to vsp contrib.
